name: Healthy Punch Card 025

on:
  workflow_dispatch:

  schedule:
  - cron: '10 16 * * 2,5,0' # UTC+8小时=北京时间 16代表凌晨零点 UTC星期+1=北京时间  2,5,0对应周三，周六，周一

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai  
      - uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3
        
      - name: requirements
        run: |
          pip3 install -r requirements.txt

      - name: Punch Card 025
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: |
          echo -n `date +%Y-%m-%d\ %H:%M:%S`\ -\ >> ./checkin025.log
          echo `date +%Y-%m-%d\ %H:%M:%S` | tee daily.log 
          echo `打卡失败` ｜tee -a daily.log
          python3 auto.py --username=$username --password=$password >> ./checkin025.log
          tail -n 2 checkin025.log | tee daily.log #避免日志上传失败丢失日志
      - name: Commit #上传日志到仓库，可以自行修改 name 和 email
        env:
         NAME: bot
         EMAIL: bot@csu-covid19.com
        run: |
          git config --global user.name "$NAME"
          git config --global user.email "$EMAIL"
          git add .
          git commit -m "bot checkin025"
      - name: Push log
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
